services:
    db:
        image: postgres:16.1
        container_name: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: secret
        ports:
            - 5432:5432
        volumes:
            - ./db:/docker-entrypoint-initdb.d
