services:
    db:
        image: postgres:16.1
        container_name: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: secret
        ports:
            - 5432:5432
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-network

    api:
        build: ./api/
        container_name: api
        ports:
            - 3000:3000
        networks:
            - app-network

    frontend:
        build: ./frontend/
        container_name: frontend
        ports:
            - 5173:5173
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
